server:
  port: 8080

spring:
  config:
    import:
      -: "classpath:product-config.yml"
  datasource:
    url: jdbc:mysql://localhost:${DATABASE.PORT}/${DATABASE.NAME}?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: ${DATABASE.USERNAME}
    password: ${DATABASE.PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20 # 初始连接数
      min-idle: 10 # 最小空闲连接数
      max-active: 100 # 最大连接数
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 序列化配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false


mybatis-plus:
  global-config:
    db-config:
      #id类型: 雪花算法实现
      id-type: assign_id
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制台打印，生产环境换日志打印
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: pojo

logging:
  #  开发阶段不持久化日志，debug模式可以看sql
  #  file:
  #    path: E:\\FinishDesigning\\log
  #    name: job.log
  level:
    com.job: debug