# 项目名(注意，该项目项目名字必须与idea创建项目时的项目名一致，就是当前idea窗口Project下面的名字)
PRODUCT_NAME: course

# 数据库名
DATABASE:
  NAME: course
# 数据库账号密码端口
  USERNAME: root
  PASSWORD: yhx123456
  PORT: 3306

# 要自动生成代码的表名
TABLE:
  -"user"
  -"course"